### ISSUE TITLE
Handle exceptions in mosrs.setup properly

### ISSUE THREAD

**Issue by penguian** [penguian/mosrs-setup#39]
Currently, a password error causes an unhandled exception. For example:
```
Please enter the MOSRS password for paulleopardi: 
svn: E170013: Unable to connect to a repository at URL 'https://code.metoffice.gov.uk/svn/test'
svn: E215004: No more credentials or we tried too many times.
Authentication failed
You can ask for help with the ACCESS systems by emailing "help@nci.org.au"

Traceback (most recent call last):
  File "/g/data/dx2/pcl900/src/mosrs-setup/install/bin/mosrs-setup", line 11, in <module>
    load_entry_point('mosrs==0.5.3', 'console_scripts', 'mosrs-setup')()
  File "build/bdist.linux-x86_64/egg/mosrs/setup.py", line 167, in main
  File "build/bdist.linux-x86_64/egg/mosrs/setup.py", line 147, in setup_mosrs_account
  File "build/bdist.linux-x86_64/egg/mosrs/auth.py", line 181, in check_or_update
  File "build/bdist.linux-x86_64/egg/mosrs/auth.py", line 163, in update
  File "build/bdist.linux-x86_64/egg/mosrs/auth.py", line 146, in check_svn_credentials
Exception: 
ERROR: Unable to access https://code.metoffice.gov.uk/svn/test via Subversion with your credentials.
```
Such exceptions should be caught and handled appropriately.

**Comment by penguian** [comment]
Closed by #41
