### ISSUE TITLE
mosrs-auth can take a long time to start

### ISSUE THREAD

**Issue by penguian** [penguian/mosrs-setup#76]
On Gadi login, `mosrs-auth` sometimes takes more than a minute to start. Using `CTRL-c` reveals:
```
mosrs-auth
^CTraceback (most recent call last):
  File "/g/data/hr22/.test/apps/mosrs-setup/0.7.3/bin/mosrs-auth", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 773, in resolve
    env = Environment(self.entries)
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 984, in __init__
    self.scan(search_path)
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1016, in scan
    for dist in find_distributions(item):
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2065, in find_on_path
    for dist in factory(fullpath):
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2135, in distributions_from_metadata
    root, entry, metadata, precedence=DEVELOP_DIST,
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2592, in from_location
    py_version=py_version, platform=platform, **kw
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2994, in _reload_version
    md_version = self._get_version()
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2772, in _get_version
    version = _version_from_file(lines)
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2558, in _version_from_file
    return safe_version(value.strip()) or None
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1331, in safe_version
    return str(packaging.version.Version(version))
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 230, in __init__
    self._version.local,
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 353, in _cmpkey
    reversed(release),
  File "/apps/python2/2.7.17/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 352, in <lambda>
    lambda x: x == 0,
KeyboardInterrupt
```

**Comment by penguian** [comment]
Close. This no longer occurs.
