### ISSUE TITLE
rsync backup sometimes fails

### ISSUE THREAD

**Issue by penguian** [penguian/mosrs-setup#91]
Using `rsync -a` sometimes fails, e.g. when using OOD VDI.
```
Traceback (most recent call last):
  File "/g/data/hr22/.test/apps/mosrs-setup/0.9.0/bin/mosrs-setup", line 11, in <module>
    load_entry_point('mosrs==0.9.0', 'console_scripts', 'mosrs-setup')()
  File "build/bdist.linux-x86_64/egg/mosrs/setup.py", line 169, in main
  File "build/bdist.linux-x86_64/egg/mosrs/setup.py", line 124, in setup_mosrs_account
  File "build/bdist.linux-x86_64/egg/mosrs/auth.py", line 123, in check_or_update
  File "build/bdist.linux-x86_64/egg/mosrs/auth.py", line 77, in update
  File "build/bdist.linux-x86_64/egg/mosrs/auth.py", line 56, in request_and_save_credentials
  File "build/bdist.linux-x86_64/egg/mosrs/svn.py", line 69, in save_svn_username
  File "build/bdist.linux-x86_64/egg/mosrs/backup.py", line 79, in backup
mosrs.exception.BackupError: Backup via rsync failed: rsync: chgrp "/home/900/rxy900/.mosrs-setup/backup.2023-01-26.1296409/.subversion/auth/svn.simple/.2be6a67d04b1c8c6d879daafa52fd762.ZFpFXN" failed: Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
```
Please investigate and remedy.

**Comment by penguian** [comment]
Closed by pull request #92
